services:
  backend:
    container_name: ${COMPOSE_PROJECT_NAME}_backend
    build:
      context: ./docker/php8.3
      network: host
      dockerfile: Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    restart: unless-stopped
    ports:
      - "${PORTA_HTTP}:80"
    environment:
      - TMPDIR=/tmp
      - TMP=/tmp
    volumes:
      - ./:/var/www/html
    depends_on:
      - cache
      - db_mysql
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app-net

  frontend:
    image: node:20-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_frontend
    user: "1000:1000"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "${PORTA_VITE}:5173"
    command: tail -f /dev/null
    depends_on:
      - backend
    networks:
      - app-net

  cache:
    image: redis:7-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_cache
    restart: unless-stopped
    ports:
      - "${PORTA_REDIS}:6379"
    volumes:
      - cache_redis:/data
    networks:
      - app-net

  db_mysql:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_db_mysql
    restart: unless-stopped
    command: --authentication_policy=mysql_native_password
    ports:
      - "${PORTA_MYSQL}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}_sistema
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-net

volumes:
  cache_redis:
  db_data:

networks:
  app-net:
    driver: bridge