# Bloco padrão para rejeitar acessos estranhos (como localhost ou o IP direto)
server {
    listen 80 default_server;
    server_name _;
    #return 404; # O 444 fecha a conexão sem dar resposta nenhuma, ou use 404.
    root /usr/share/nginx/html;
    rewrite ^(.*)$ /erro_url.html break;
}

server {
    listen 80;
    server_name sistema.interno 192.168.18.65; # O domínio que você digita no navegador
    
    client_body_temp_path /var/nginx_tmp 1 2;
    client_max_body_size 2000M;
        # ATIVAR MANUTENÇÃO: Remova o '#' das duas linhas abaixo para ligar
        # error_page 503 @manutencao;
        # return 503;

    location @manutencao {
        # O Nginx vai buscar dentro da pasta que mapeamos no Compose
        root /usr/share/nginx/html;
        rewrite ^(.*)$ /manutencao.html break;
    }

    location / {
        # O Nginx joga o tráfego direto para o nome do serviço do Docker na porta 80
        proxy_pass http://backend:80; 

        # Repassa os cabeçalhos originais do usuário (evita problemas de CORS/Redirecionamento)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Força o backend a achar que o domínio acessado foi 'sistema.local'
        #proxy_set_header Host sistema.local;
        
        #proxy_set_header X-Real-IP $remote_addr;
        #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_set_header X-Forwarded-Proto $scheme;
    }
 
}
