server {
    listen 80;
    server_name sistema2.local; # O domínio que você digita no navegador

    location / {
        # O Nginx joga o tráfego direto para o nome do serviço do Docker na porta 80
        proxy_pass http://backend2:80; 
        
        # Repassa os cabeçalhos originais do usuário (evita problemas de CORS/Redirecionamento)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}